### ISSUE TITLE
Electron 28-based Testing Release - report of compatibility

### ISSUE THREAD

**Issue by ask2018** [win32ss/supermium-electron#2]
Hello,
thank you very much for first testing release. I'm opening this issue to report here what is working fine and what not.
I've tested 2 electron based applications on Windows 7 x64 SP1 with all updates ESU included

1. ElectronMail https://github.com/vladimiry/ElectronMail/ - tested version 5.2.0
This seems to be working fine. Or at least I didn't find issues yet.

2. Tutanota Desktop https://github.com/tutao/tutanota - tested version 3.118.8
Application just opens and exits with no error or warning.

**Comment by win32ss** [comment]
Tutanota is launching for me on Vista, 7 and 10 1809. Did you make sure that the ```resources``` folder was cleaned out before copying in Tutanota's files?

Or you can keep only default_app.asar (it's needed to direct Electron to other paths for finding applications) in ```resources``` and launch Tutanota from elsewhere by the command line (type ``` electron X:\resources\app.asar``` where resources is Tutanota's resources folder).

In fact, I will make an Electron app manager to prevent these conflicts and allow a user to launch multiple applications easily.

**Comment by win32ss** [comment]
I will also report that GitHub Desktop works:
![image](https://github.com/win32ss/supermium-electron/assets/93808768/ca113639-595e-4e02-b9bb-01ca91894de2)

However, Supermium Electron on Vista only launches from the command line or it loops. This issue does not affect 7 and above so I decided to release it.

**Comment by ask2018** [comment]
Yes I've cleaned that folder. But I have found already what is causing that crash for Tutanota for me.
I cleaned my  C:\Users\USERNAME\AppData\Roaming\tutanota-desktop folder and tried to run it again. 
Now there was no crash. I've tried to login to my account and that is working as well.
But If I try to tick "save my login details" and try to login it crashes. Same if the login details are already saved from previous version. Crash must be related somehow to this and you need tutanota account for testing it.

**Comment by win32ss** [comment]
The crash is in the better-sqlite3 node module. It happens regardless of OS, so presumably it is related to something missing from Supermium Electron. I also tried Tutanota with VS Code 1.83 Insider's Electron executable and the same thing happens.

**Comment by ask2018** [comment]
I've tried older versions of Tutanota and last version without this crash seems to be 3.114.1 (but I'm getting there some errors on start and close). 
With 3.115.2 I have already the same crash as with 3.118.8.

**Comment by MVoloshin** [comment]
![image](https://github.com/win32ss/supermium-electron/assets/11507146/34dd1099-fd73-4261-bdaf-5655ecd3ff69)

ArmCord 3.2.4 (latest version of Discord fork). Didn't notice any glitches yet

**Comment by ask2018** [comment]
I'm facing similar crash issue as with Tutanota with Session. It is also using better-sqlite3 node module, so it might be the same reason of the crash. I can run it, but right after I input my password, it crashes.
https://github.com/oxen-io/session-desktop
Tested version 1.11.3

**Comment by win32ss** [comment]
I tried using the version of better-sqlite3 that is in Tutanota 3.114.1 with 3.118.8 and there was no change. I will build better-sqlite3 from source to get debugging symbols and try to get a clearer idea of what is happening.

**Comment by MiraakThuri** [comment]
Windows 7 X64 SP1
Not working on Discord official client (last version):
![Capture2](https://github.com/win32ss/supermium-electron/assets/69920875/35c05d1a-11fb-46ab-84be-8cbee9f7fc07)

Also tried to use OpenAsar (https://github.com/GooseMod/OpenAsar) (superlight opensource replacement for Discord app.asar)
but i will get this error:
![Capture](https://github.com/win32ss/supermium-electron/assets/69920875/c094ad42-2923-4f3c-babb-4e253724d122)

I know other clients like ArmCord exists but since they are based on the Web version they lacks alot of the features im using such as custom keybinds and exclusive fullscreen game screensharing

PS: Make no difference if i start discord using the commandline to start the App.asar from the source folder

**Comment by sergeevabc** [comment]
Anyone care to provide pre-built .zip to download and replace incompatible Electron-based app files? I'd like to test it with Obsidian (another popular Electron-based app).

**Comment by ask2018** [comment]
@sergeevabc for now you can grab precompiled testing build here: https://github.com/win32ss/supermium-electron/releases/tag/v28-testing and I guess @win32ss will provide stable build when it will be ready for more testing.

**Comment by sergeevabc** [comment]
@ask2018, alright, reporting back.
Tested x64 with Obsidian, does not work, dark empty screen.

**Comment by KandiPanda** [comment]
Tested the precompile build with https://github.com/FreeTubeApp/FreeTube, and 64-bit Supermium-Electron does work with [nightly build freetube-0.19.1-nightly-3736](https://github.com/FreeTubeApp/FreeTube/actions/runs/7201254253) onwards (at least as of [current latest build as of this writing](https://github.com/FreeTubeApp/FreeTube/actions/runs/7278585188)). 

Edit: Current release ([Release v0.20.0 Beta](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.20.0-beta)) works in 64-bit Supermium-Electron, have not tested in 32-bit but would _guess_ that it _should_ work there as well.

Edit: Tested [the current latest build (freetube-0.20.0-nightly-4263)](https://github.com/FreeTubeApp/FreeTube/actions/runs/8882557713) in both 64-bit and 32-bit Supermium-Electron, seems to work fine in either.

Edit: [freetube-0.21.3-nightly-4681](https://github.com/FreeTubeApp/FreeTube/actions/runs/10560734729) is still working in 64-bit Supermium-Electron, haven't checked with 32-bit in a while but would think that it would work there also.

**Comment by malisipi** [comment]
[NewFlow](https://github.com/malisipi/NewFlow) is currently working fine in Windows 7 with Supermium Electron.

![win7](https://github.com/win32ss/supermium-electron/assets/87281783/2529f368-a11d-4833-a574-e3226c4e4505)

**Comment by Jevil7452** [comment]
Beeper (http://beeper.com/) works fine
![image](https://github.com/win32ss/supermium-electron/assets/98893064/97f33608-a1a0-425e-a4fe-b6b1c30893a6)

**Comment by Jevil7452** [comment]
Vencord Desktop/Vesktop (https://github.com/Vencord/Vesktop) works fine
![image](https://github.com/win32ss/supermium-electron/assets/98893064/a61e676b-1ff4-4d0c-be20-88c08b5ac267)

**Comment by Kazcade** [comment]
@KandiPanda
> Tested the precompile build with https://github.com/FreeTubeApp/FreeTube, and 64-bit Supermium-Electron does work with [nightly build freetube-0.19.1-nightly-3736](https://github.com/FreeTubeApp/FreeTube/actions/runs/7201254253) onwards (at least as of [current latest build as of this writing](https://github.com/FreeTubeApp/FreeTube/actions/runs/7278585188)).
> 
> Edit: Current release ([Release v0.20.0 Beta](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.20.0-beta)) works in 64-bit Supermium-Electron, have not tested in 32-bit but would _guess_ that it _should_ work there as well.
> 
> Edit: Tested [the current latest build (freetube-0.20.0-nightly-4263)](https://github.com/FreeTubeApp/FreeTube/actions/runs/8882557713) in both 64-bit and 32-bit Supermium-Electron, seems to work fine in either.

No idea if this is still relevant, given the lack of updates, but trying this with the latest version of Freetube (v0.21.0 Beta) I am running into issue when opening additional windows inside the app - doing so results in the prior windows going blank and becoming unresponsive:

![Untitled](https://github.com/win32ss/supermium-electron/assets/38895974/b7d0c287-0742-4c1b-9c51-9789eab1824d)

Opening the dev console prior to this outputs the following info:

![Untitled2](https://github.com/win32ss/supermium-electron/assets/38895974/e49f7c5e-8f2b-4499-bc8c-fc230c99ae21)

Reloading the window usually results in the _other_ window blanking out, but occasionally results in both windows working, at least until any other action is taken.

I don't know if this due to an inherent limitation of Supermium or a compatibility issue with freetube. Can anybody replicate this issue? At least for me this greatly impacts usability and any fix for this would be welcome.

ADDENDUM:

This seems to be related to the number of subscribed channels, but i have no idea why. The bug does not occur (or extremely rarely, I was not able to recreate it) with a newly created profile and no saved channels/subscriptions, but after a certain number of channels have been added electron will occasionally throw the above "blank window" bug after a new channel is added - even when no other actions is taken beside pressing the "subscribe" button (i.e. no video is played). This starts to get more frequent when the list hits 40-50 channels and at about 100 channels (my current list is ~106 channels) this happens once for every 8-10 channels that are newly added. This can also be triggered by repeatedly re-subscribing to a single channel.

As the list gets larger, the number of concurrent windows that can be opened before the bug occurs gets increasingly smaller - for ~50 subscribed channels the number of usable windows is around 10, while at ~100 channels it's about 2-3 - at that point opening a new window blanks the oldest existing window.

According to ProcExplorer the process that crashes/terminates is the electron renderer (electron.exe --type=renderer...), not the utility or gpu process.

Any help in troubleshooting this would be appreciated.

**Comment by KandiPanda** [comment]
@Kazcade 

Haven't had that issue myself, and I'm at 70 channels currently, though I only occasionally open multiple simultaneous windows. 

How are you opening the new windows? Center-clicking something in the current one, as I do? (Also tried the "new window" button at the top out of curiosity and didn't seem to have an issue with it.)
And are you combining Supermium-Electron and FreeTube the way I am, by deleting the placeholder resources folder from Supermium-Electron and copying over the one from the FreeTube zip file?

Other visible difference I see is that I have **Settings > Distractions > Side Bar > Hide Active Subscriptions** enabled, may see if that helps any? (Also less importantly, I have **Settings > Theme Settings > Expand Side Bar by Default** and **Settings > Theme Settings > Hide Side Bar Labels** both disabled.)

(Just in case it's relevant, current specs are i7-940 CPU, GTX 1070 SC, 3x4GB RAM, and Windows 7 Ultimate using the Windows Classic theme.)

Also as a side note, you'll want to upgrade to v0.21.1 Beta, it has some upstream fixes in it for a couple major issues that recently developed from changes on YouTube's side: 

> Summary
> 
> - This release fixes the recent major issue of videos unable to play when using the Local API.
> 
> Fixes
> 
> - Update YouTube.js which fixes the recent video playback issue with the local API by @PikachuEXE in https://github.com/FreeTubeApp/FreeTube/pull/5384
> - Fixed an issue where the scroll down arrow in the live chat window would persist even if you scrolled to the bottom by @kommunarr in https://github.com/FreeTubeApp/FreeTube/pull/5302
> -  Fixed an issue where navigating away from an age-restricted video would cause the app to lock out by @absidue in https://github.com/FreeTubeApp/FreeTube/pull/5343
> - Fixed an issue where toast messages during Invidious API errors would not show a proper error message by @absidue in https://github.com/FreeTubeApp/FreeTube/pull/5380
> - Fixed an issue where generating DASH manifest files were not being done properly when using the Invidious API by @absidue in https://github.com/FreeTubeApp/FreeTube/pull/5387

**Comment by Kazcade** [comment]
@KandiPanda

Thanks for the heads-up, I had already upgraded to 0.21.1 on my other devices and did so on my desktop this morning, unfortunately it didn't change in regards to the bug.

>How are you opening the new windows? Center-clicking something in the current one, as I do?

That or left-clicking on the "open new window" button next to the search bar. Doesn't make a difference, even the "new window" from the title bar ("Alt") triggers the bug.

>Other visible difference I see is that I have Settings > Distractions > Side Bar > Hide Active Subscriptions enabled, may see if that helps any?

It looks like it is indeed the subscription sidebar itself that is causing the buggy behaviour, as enabling "Hide Active Subscriptions" appears to fix the issue - I was unable to trigger the bug even when opening 20+ windows during testing. _Thanks for pointing that out._

In contrast to that, loading the "Channels" window multiple times (and opening videos in parallel) doesn't cause any issues. Weird.

A bit unfortunate being unable to utilize the sidebar, but usable. Still, I'd be interested as to why the sidebar (and loading the list of subscriptions in particular) leads to the instance crashing. Is there any way to enable logging for electron? The crash does not appear in the console output from what I can tell, the window simply outputs that the devtools were disconnected (as per my prior post).

**Comment by Jevil7452** [comment]
![image](https://github.com/user-attachments/assets/6271b047-a1f1-4e20-9120-af7187e99a32)
It doesn't work with ArmCord 3.3.0
![image](https://github.com/user-attachments/assets/06ee6373-523e-4149-9ddd-0401f01a96c0)
ArmCord 3.2.8 works fine

**Comment by KandiPanda** [comment]
Ran into an issue with [freetube-0.21.3-nightly-4694](https://github.com/FreeTubeApp/FreeTube/actions/runs/10659620267) in Supermium-Electron, which persists in 4698 (currently the latest nightly). 

Using Alt-Left or Alt-Right (or Back/Forward in the View dropdown menu, see attached image) to go forward/back throws an error (see attached image) and do not go forward/back. (the error can be closed and FreeTube will otherwise continue to function). 
![image](https://github.com/user-attachments/assets/5d667fd2-bbb6-4642-9e53-3392ba897171)
![image](https://github.com/user-attachments/assets/37686d7d-c50f-4d71-8f51-7818790475ba)

The left/right arrows near the top of the window (see attached image) and using `history.back()` and `history.forward()` in the console both still work fine. (Edit: The forward/back buttons on the side of the mouse also still work fine.)
![image](https://github.com/user-attachments/assets/494bc838-8183-4df7-bbeb-cc8824d13484)

It appears that the PR causing the issue is https://github.com/FreeTubeApp/FreeTube/pull/5626 ("Switch to non-deprecated Electron navigation history APIs") which replaces `webContents#goForward()` and `webContents#goBack()` with `webContents#navigationHistory#goForward()` and `webContents#navigationHistory#goForward()` in one place each. 

(Side note, is there any chance of there being some way that I can shim Supermium-Electron for this?)

**Comment by KandiPanda** [comment]
Update on FreeTube compatability: 

Versions up to [v0.22.1-nightly-5363 Beta](https://github.com/FreeTubeApp/FreeTube/actions/runs/12517845760) seem to work at least as well as previous versions. 

Versions [v0.22.1-nightly-5364 Beta](https://github.com/FreeTubeApp/FreeTube/actions/runs/12520078255) (implementing https://github.com/FreeTubeApp/FreeTube/pull/6436) and later (as of when I'm posting this message) are throwing the error `Error: Error invoking remote method 'generate-po-token': ReferenceError: crypto is not defined` on Local API (and at the moment various assorted errors on Invidious API, though that may just be a temporary Invidious issue).

I haven't tested the official FreeTube nightly (rather than its resources folder in Supermium-Electron) since I already know that it won't run on Win7, and I don't have Win10+ installed.

**Comment by bt4ibwem8** [comment]
@KandiPanda 
Did you test the last beta? https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.22.1-beta

edit: i just tested it now and it works :)

**Comment by KandiPanda** [comment]
@bt4ibwem8 
Release v0.22.1-beta (which you linked to) is _older_ than v0.22.1-nightly-5363 Beta (the one I mentioned as working) and v0.22.1-nightly-5364 Beta (the one that's failing for me). 

Also I just tested with v0.22.1-nightly-5429 Beta (which was built minutes ago at this time) and it's still failing with the same errors when you try to actually watch any videos. 

Next time they do a release rather than just a nightly build (likely whenever YouTube does something that will stop older versions from playing videos as well), then the release will probably do the same thing that the nightly builds have been doing since 5364.

**Comment by KandiPanda** [comment]
Oh, here's the full error from the console (rather than just the short version that pops up) if it'll help someone figure out a fix... 
(It kind of appears to be an issue with Supermium-Electron not playing nice with something, since it's been doing it with all the nightlies for a couple weeks now, and if it was an issue with FreeTube itself then I'd think that it would do it in the official Electron that they use also and that they would have addressed it by now since it prevents any videos from loading/playing, but I haven't heard any mentions of it happening except with Supermium-Electron...)

`renderer.js:2 Error: Error invoking remote method 'generate-po-token': ReferenceError: crypto is not defined`
`    at EventEmitter.invoke (node:electron/js2c/renderer_init:2:9975)` 
`    at async rY (renderer.js:2:1792074)`
`    at async r.getVideoInformationLocal (renderer.js:2:2247220)`
`getVideoInformationLocal @ renderer.js:2`

**Comment by bt4ibwem8** [comment]
Also the list of subscribed channels does not work in Freetube, empty page is loaded. Everything else seems to work fine.

**Comment by swinokur** [comment]
the new beta of beeper https://www.beeper.com/beta does not work with electron (Beeper Beta Setup 4.0.397). 

![Image](https://github.com/user-attachments/assets/5502d7c7-badc-47a0-b72f-d62aa92e6f0a)

package.json:
{
  "name": "BeeperTexts",
  "friendlyProductName": "Beeper",
  "version": "4.0.397",
  "description": "The ultimate messaging app",
  "main": "build/main/index.mjs",
  "dependencies": {
    "@beeper/beeper-client-sdk": "3.0.0-latest",
    "better-sqlite3": "npm:@signalapp/better-sqlite3@9.0.8",
    "cbor-extract": "^2.2.0",
    "classic-level": "^2.0.0",
    "diskusage": "https://github.com/TextsHQ/diskusage#6a3e1d186ba3b406c3525bcaff0ed8d77c6ec4f7",
    "electron-drag-click": "1.0.6",
    "keytar": "^7.9.0"
  },
  "optionalDependencies": {
    "bufferutil": "^4.0.7",
    "global-mouse-events": "^1.2.0",
    "node-mac-contacts": "https://github.com/TextsHQ/node-mac-contacts.git#main",
    "node-mac-permissions": "https://github.com/TextsHQ/node-mac-permissions.git#main",
    "utf-8-validate": "^5.0.10",
    "credential-extractor": "https://github.com/TextsHQ/credential-extractor"
  },
  "resolutions": {
    "nan": "^2.17.0",
    "node-gyp": "^10.0.1"
  }
}

the release version 3.110.1 still works fine, hopefully there will be a new supermium-electron soon

**Comment by KenCorma** [comment]
@win32ss Been working on a v30 of electron got a exe built but has some issues 
Would love some help. 
https://github.com/KenCorma/supermium-electron/releases/tag/v30.5.1
https://github.com/KenCorma/electron-supermium/discussions/1

**Comment by swinokur** [comment]
@win32ss - I was wondering if there might be any updates on a v30 of supermium-electron?! thanks!

**Comment by KenCorma** [comment]
> [@win32ss](https://github.com/win32ss) - I was wondering if there might be any updates on a v30 of supermium-electron?! thanks!

Go here I have a build working 
https://github.com/KenCorma/electron-supermium/discussions

**Comment by swinokur** [comment]
Just putting this here in case it helps: 
https://github.com/KenCorma/electron-supermium/discussions/1#discussioncomment-13687034

> There is a repository that patches Node.js LTS releases to work on Windows 7 as a helper to get Node 20 working: https://github.com/vladimir-andreevich/node.js-windows-7
